version: '3.3'
services:
  prodserver:
    image: rastasheep/ubuntu-sshd:16.04
    networks:
      - vc
      - traefik
    deploy:
      labels:
        traefik.docker.network: traefik
        traefik.port: 4200
        traefik.frontend.rule: Host:ets2.virtual-company.de
  devserver:
    image: rastasheep/ubuntu-sshd:16.04
    networks:
      - vc
      - traefik
    ports:
      - 8888:22
    volumes:
      - data:/usr/src/
    deploy:
      labels:
        traefik.docker.network: traefik
        traefik.port: 4200
        traefik.frontend.rule: Host:ets2-dev.virtual-company.de
  mongo:
    image: mongo:3.5
    networks:
      - vc
    volumes:
      - db:/data/db

networks:
  vc:
    driver: overlay
  traefik:
    external: true

volumes:
  data:
    driver: local
  db:
    driver: local
