version: '3.1'
services:
  nodebb:
    image: fankserver/nodebb
    networks:
      - forum
    volumes:
      - app:/usr/src/app
    ports:
      - 4567:4567
  mongo:
    image: mongo
    networks:
      - forum
    volumes:
      - mongo:/data/db

networks:
  forum:
    driver: overlay

volumes:
  mongo:
    driver: local
  app:
    driver: local
